from django.urls import path
from .views import (
    GetQuizzesView, 
    ContinueSessionView, 
    ProcessMessageView, 
    ParticipatedQuizzesView, 
    RetryMissedQuestionView, 
    RetryableScoresView, 
    RetrySessionStatusView,
    ClearRetrySessionView,
    AddQuizView,
    MyQuizzesView,
    UpdateQuizStatusView,
    DeleteQuizView,
    EditQuizNameView,
    GrantQuizAccessView,
    QuizAccessListView,
    ListCategoriesView,
    CategoriesWithQuizzesView,
    QuizzesByCategoryView
    )

urlpatterns = [
    path('quiz/get_quizzes/', GetQuizzesView.as_view()),
    path("quiz/continue_session/", ContinueSessionView.as_view()),
    path("quiz/process_message/", ProcessMessageView.as_view()),
    path("quiz/get_participated_quizzes/", ParticipatedQuizzesView.as_view()),
    path("quiz/retry_missed_question/", RetryMissedQuestionView.as_view()),
    path("quiz/get_retryable_scores/", RetryableScoresView.as_view()),
    path("quiz/retry_session_status/", RetrySessionStatusView.as_view()),
    path("quiz/clear_retry_session/", ClearRetrySessionView.as_view()),
    path("quiz/add_quiz/", AddQuizView.as_view()),
    path("quiz/get_my_quizzes/", MyQuizzesView.as_view()),
    path("quiz/update_quiz_status/", UpdateQuizStatusView.as_view()),
    path('quiz/delete_quiz/', DeleteQuizView.as_view()),
    path('quiz/edit_quiz_name/', EditQuizNameView.as_view()),
    path("quiz/grant_quiz_access/", GrantQuizAccessView.as_view()),
    path("quiz/get_quiz_access_list/", QuizAccessListView.as_view()),
    path("quiz/list_categories/", ListCategoriesView.as_view()),
    path("quiz/categories_with_quizzes/", CategoriesWithQuizzesView.as_view()),
    path("quiz/quizzes_by_category/", QuizzesByCategoryView.as_view()),
]
