# Generated by Django 5.0.12 on 2025-06-27 14:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizscore',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizscore',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
