# Generated by Django 5.0.12 on 2025-06-28 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_quiz_quizscore_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.quizparticipant')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.quiz')),
                ('score_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.quizscore')),
            ],
        ),
    ]
