# Generated by Django 5.0.12 on 2025-06-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_quizsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='questions',
            field=models.JSONField(default=list),
        ),
    ]
