# Generated by Django 5.0.12 on 2025-06-29 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_quizsession_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='quiz_app.quizparticipant'),
        ),
        migrations.AddField(
            model_name='quizparticipant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
