# Generated by Django 5.0.12 on 2025-06-29 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_quiz_participant_quizparticipant_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizparticipant',
            options={'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
        migrations.AlterModelOptions(
            name='quizscore',
            options={'ordering': ['-attempt_time']},
        ),
        migrations.AlterField(
            model_name='quizparticipant',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='quizparticipant',
            name='telegram_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='quizscore',
            name='end_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='quiz_app.quizparticipant'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='quiz_app.quiz'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='score_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='quiz_app.quizscore'),
        ),
    ]
