# Generated by Django 5.0.12 on 2025-07-01 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0008_quiz_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('full_access', 'Full Access'), ('participate_access', 'Participate Access')], default='participate_access', max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_accesses', to='quiz_app.quizparticipant')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessible_quizzes', to='quiz_app.quizparticipant')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='quiz_app.quiz')),
            ],
            options={
                'verbose_name': 'Quiz Access',
                'verbose_name_plural': 'Quiz Accesses',
                'unique_together': {('quiz', 'participant')},
            },
        ),
    ]
