# Generated by Django 5.0.12 on 2025-07-01 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0010_quizscore_missed_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetryQuizScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0, editable=False)),
                ('missed_questions', models.JSONField(blank=True, default=list)),
                ('index', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('original_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retry_attempts', to='quiz_app.quizscore')),
            ],
        ),
    ]
