# Generated by Django 5.0.12 on 2025-07-02 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0011_retryquizscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetrySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('expecting_answer', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.quizparticipant')),
                ('retry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.retryquizscore')),
            ],
        ),
    ]
