# Generated by Django 5.0.12 on 2025-07-04 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0014_quizcategory_quiz_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizcategory',
            name='icon',
        ),
    ]
