# Generated by Django 5.0.12 on 2025-07-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0015_remove_quizcategory_icon'),
    ]

    operations = [
    ]
